In [1]:
dictionary =  {'il': 1, 'gatto': 2, 'mangia': 3, 'topo': 4, 'miagola': 5, 'cane': 6, 'abbaia': 7, 'formaggio': 8, 
               'bimbo': 9, 'chiama': 10, 'la': 11, 'mamma': 12, 'pappa': 13, 'piange': 14, 'e': 15, 'giocano': 16, 
               ' ': 0}

In [2]:
def inOutExperiments(i0,i1,i2):
    inExp=[0,0,0]
    inExp[0]=(1/16)*dictionary[i0]
    inExp[1]=(1/16)*dictionary[i1]
    inExp[2]=(1/16)*dictionary[i2]

    test_outputs = forward_pass_with_activations([inExp])
    ou=[round(16*test_outputs[0]),round(16*test_outputs[1])]

    # Find all keys for the values in ou
    for v in ou:
        keys = [key for key, val in dictionary.items() if val == v]
        print(keys)  

In [3]:
# preparato da Copilot via WhatsApp
import numpy as np
import csv

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# ANN parameters
input_nodes = 3
hidden_nodes = 10
output_nodes = 2
learning_rate = 0.01
epochs = 200000

# Initialize weights randomly
#np.random.seed(42)
weights_input_hidden = np.random.rand(hidden_nodes, input_nodes + 1) - 0.5  # +1 for bias
weights_hidden_output = np.random.rand(output_nodes, hidden_nodes + 1) - 0.5  # +1 for bias

# Training phase
def train(inputs, expected_output):
    global weights_input_hidden, weights_hidden_output
    
    inputs_with_bias = np.append(inputs, 1)  # Add bias to inputs
    hidden_inputs = np.dot(weights_input_hidden, inputs_with_bias)
    hidden_outputs = sigmoid(hidden_inputs)
    
    hidden_outputs_with_bias = np.append(hidden_outputs, 1)  # Add bias to hidden outputs
    final_inputs = np.dot(weights_hidden_output, hidden_outputs_with_bias)
    final_outputs = sigmoid(final_inputs)
    
    # Error calculation
    output_error = expected_output - final_outputs
    hidden_error = np.dot(weights_hidden_output[:, :-1].T, output_error) * sigmoid_derivative(hidden_outputs)

    # Update weights
    weights_hidden_output += learning_rate * np.outer(output_error * sigmoid_derivative(final_outputs), hidden_outputs_with_bias)
    weights_input_hidden += learning_rate * np.outer(hidden_error, inputs_with_bias)

# Forward application phase with activations display
def forward_pass_with_activations(inputs):
    inputs_with_bias = np.append(inputs, 1)  # Add bias to inputs
    hidden_inputs = np.dot(weights_input_hidden, inputs_with_bias)
    hidden_outputs = sigmoid(hidden_inputs)
    
    print("Activation levels of hidden nodes (before bias):")
    print(hidden_outputs)
    
    hidden_outputs_with_bias = np.append(hidden_outputs, 1)  # Add bias to hidden outputs
    final_inputs = np.dot(weights_hidden_output, hidden_outputs_with_bias)
    final_outputs = sigmoid(final_inputs)
    
    print("\nActivation levels of output nodes:")
    print(final_outputs)
    
    return final_outputs

# Example data
training_inputs =[]
with open("in.txt", newline='') as csvfile:
    reader= csv.reader(csvfile, delimiter=',', quoting=csv.QUOTE_NONNUMERIC)
    for row in reader:
        training_inputs.append(row)
training_outputs =[]
with open("ou.txt", newline='') as csvfile:
    reader= csv.reader(csvfile, delimiter=',', quoting=csv.QUOTE_NONNUMERIC)
    for row in reader:
        training_outputs.append(row)

# Train the network
for epoch in range(epochs):
    for i in range(len(training_inputs)):
        train(training_inputs[i], training_outputs[i])

# Display final weight matrices
print("Weights from input to hidden layer after learning:")
print(weights_input_hidden)
print("\nWeights from hidden to output layer after learning:")
print(weights_hidden_output)



Weights from input to hidden layer after learning:
[[ -0.71465154  -0.3210302    0.49648906   4.59054407]
 [ -0.94954208  -1.63647719  -0.20193654  -3.3737532 ]
 [ -1.42641956  18.25880013   0.12892864 -10.89382418]
 [-12.65019042  -0.84481663  23.80123136   0.28621028]
 [  2.64642418   1.48924305  -1.53038753   5.46379958]
 [ -3.33884245  -4.07165293  -1.22119115   4.28568956]
 [ -0.61164728   1.07353045  -1.4058122   -6.06435088]
 [  4.74788717   0.82536031  -2.06809244   6.66366344]
 [  0.20192428  -0.1881289    1.66940678   5.20337446]
 [  1.73374194  -0.79202101  -0.30573034   5.92790689]]

Weights from hidden to output layer after learning:
[[-0.58555804 -0.09061149  8.50415442 -2.76610198  0.90663767 -1.55374768
   1.98298431  0.4087315  -0.63589377 -0.38817646  2.05426396]
 [-0.33929426  0.47172414  6.06215517  7.93183165 -2.59263129  0.95161749
   0.35347361 -3.95034648 -1.05794639 -1.52583649 -0.06470328]]


  
casistica  

il,gatto,mangia,>,il,topo  
il,gatto,>,miagola  
il,cane,mangia,>,il,gatto  
il,cane,>,abbaia  
il,topo,mangia,>,il,formaggio  
il,bimbo,chiama,>,la,mamma  
il,bimbo,mangia,>,la,pappa  
il,bimbo,>,piange  
bimbo,e,gatto,>,giocano  

0 per le posizioni vuote

In [4]:
ou=inOutExperiments("il","bimbo"," ")

Activation levels of hidden nodes (before bias):
[0.98744868 0.01269692 0.32906867 0.27296402 0.99844838 0.85652309
 0.00407534 0.999404   0.99400116 0.99628166]

Activation levels of output nodes:
[0.92347149 0.01071201]
['e']
[' ']
